# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ansible-powerplay 1.4.2 ruby lib

Gem::Specification.new do |s|
  s.name = "ansible-powerplay".freeze
  s.version = "1.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Fred Mitchell".freeze]
  s.date = "2016-12-26"
  s.description = "Ansible Powerplay, by way of its DSL, allows you to\n                       specify your Ansible playbooks and their vars, and common\n                       vars to all, so that you can run your\n                       indeoendent playbooks in full parallel.".freeze
  s.email = "fred.mitchell@gmx.de".freeze
  s.executables = ["powerplay".freeze, "pp".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.org"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-version",
    ".semver",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.org",
    "RELEASE_NOTES.org",
    "Rakefile",
    "SCRATCHPAD.org",
    "ansible-powerplay.gemspec",
    "bin/powerplay",
    "bin/pp",
    "examples/playbooks/dat.yml",
    "examples/playbooks/elasticseach.yml",
    "examples/playbooks/first.yml",
    "examples/playbooks/nat.yml",
    "examples/playbooks/rabbitmq.yml",
    "examples/playbooks/rat.yml",
    "examples/playbooks/second.yml",
    "examples/playbooks/seq-example.yml",
    "lib/ansible-powerplay.rb",
    "lib/ansible-powerplay/cli.rb",
    "lib/ansible-powerplay/dsl.rb",
    "lib/ansible-powerplay/powerplay.rb",
    "spec/ansible-powerplay_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/flajann2/ansible-powerplay".freeze
  s.licenses = ["MIT".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.2".freeze)
  s.rubygems_version = "2.6.8".freeze
  s.summary = "Powerplay enables you to run Ansible playbooks in parallel.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>.freeze, ["~> 0"])
      s.add_runtime_dependency(%q<term-ansicolor>.freeze, ["~> 1"])
      s.add_runtime_dependency(%q<colorize>.freeze, ["~> 0"])
      s.add_runtime_dependency(%q<semver>.freeze, ["~> 1"])
      s.add_runtime_dependency(%q<queue_ding>.freeze, ["~> 0"])
      s.add_runtime_dependency(%q<concurrent-ruby>.freeze, ["~> 1"])
      s.add_runtime_dependency(%q<awesome_print>.freeze, ["~> 1"])
      s.add_runtime_dependency(%q<json>.freeze, [">= 2.0.2", "~> 2.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3"])
      s.add_development_dependency(%q<yard>.freeze, ["~> 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<guard>.freeze, ["~> 2"])
      s.add_development_dependency(%q<guard-rspec>.freeze, ["~> 1"])
      s.add_development_dependency(%q<pry>.freeze, ["~> 0"])
      s.add_development_dependency(%q<pry-byebug>.freeze, ["~> 3"])
      s.add_development_dependency(%q<pry-doc>.freeze, ["~> 0"])
      s.add_development_dependency(%q<pry-remote>.freeze, ["~> 0"])
      s.add_development_dependency(%q<pry-rescue>.freeze, ["~> 1"])
      s.add_development_dependency(%q<pry-stack_explorer>.freeze, ["~> 0"])
    else
      s.add_dependency(%q<thor>.freeze, ["~> 0"])
      s.add_dependency(%q<term-ansicolor>.freeze, ["~> 1"])
      s.add_dependency(%q<colorize>.freeze, ["~> 0"])
      s.add_dependency(%q<semver>.freeze, ["~> 1"])
      s.add_dependency(%q<queue_ding>.freeze, ["~> 0"])
      s.add_dependency(%q<concurrent-ruby>.freeze, ["~> 1"])
      s.add_dependency(%q<awesome_print>.freeze, ["~> 1"])
      s.add_dependency(%q<json>.freeze, [">= 2.0.2", "~> 2.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3"])
      s.add_dependency(%q<yard>.freeze, ["~> 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<guard>.freeze, ["~> 2"])
      s.add_dependency(%q<guard-rspec>.freeze, ["~> 1"])
      s.add_dependency(%q<pry>.freeze, ["~> 0"])
      s.add_dependency(%q<pry-byebug>.freeze, ["~> 3"])
      s.add_dependency(%q<pry-doc>.freeze, ["~> 0"])
      s.add_dependency(%q<pry-remote>.freeze, ["~> 0"])
      s.add_dependency(%q<pry-rescue>.freeze, ["~> 1"])
      s.add_dependency(%q<pry-stack_explorer>.freeze, ["~> 0"])
    end
  else
    s.add_dependency(%q<thor>.freeze, ["~> 0"])
    s.add_dependency(%q<term-ansicolor>.freeze, ["~> 1"])
    s.add_dependency(%q<colorize>.freeze, ["~> 0"])
    s.add_dependency(%q<semver>.freeze, ["~> 1"])
    s.add_dependency(%q<queue_ding>.freeze, ["~> 0"])
    s.add_dependency(%q<concurrent-ruby>.freeze, ["~> 1"])
    s.add_dependency(%q<awesome_print>.freeze, ["~> 1"])
    s.add_dependency(%q<json>.freeze, [">= 2.0.2", "~> 2.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3"])
    s.add_dependency(%q<yard>.freeze, ["~> 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<guard>.freeze, ["~> 2"])
    s.add_dependency(%q<guard-rspec>.freeze, ["~> 1"])
    s.add_dependency(%q<pry>.freeze, ["~> 0"])
    s.add_dependency(%q<pry-byebug>.freeze, ["~> 3"])
    s.add_dependency(%q<pry-doc>.freeze, ["~> 0"])
    s.add_dependency(%q<pry-remote>.freeze, ["~> 0"])
    s.add_dependency(%q<pry-rescue>.freeze, ["~> 1"])
    s.add_dependency(%q<pry-stack_explorer>.freeze, ["~> 0"])
  end
end

