---
- hosts: local
  connection: local
  gather_facts: False
  tasks:
    - name: setting a fact
      set_fact:
        nat:
          - { 00 : nat, 01 : hello, 02 : world }
    - name: test fact and passed in variables
      debug:
        msg: "NAT test {{nat}} stack {{stack}} AWS instance type {{krell_type}} AWS disk size {{krell_disk_size}}"
